#!/usr/bin/env python3
"""Write CI Doctor PR body to /tmp/pr-body.md"""
import os
from pathlib import Path

error_count = os.environ.get("ERROR_COUNT", "0")
remaining = os.environ.get("REMAINING", "0")
errors_txt = Path("/tmp/tsc-errors.txt").read_text()[:2000]

body = f"""## CI Doctor Auto-Fix 🤖

This PR was **automatically created** after TypeScript build errors were detected on `main`.

**Error count before fix:** {error_count}
**Remaining errors:** {remaining}

### Errors
```
{errors_txt}
```

> **Please review before merging.**

🤖 *Auto-generated by CI Doctor*
"""

Path("/tmp/pr-body.md").write_text(body)
print("PR body written")
