/**
 * Simple Offer Redemption Test
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import Offer from '../src/models/Offer';
import { User } from '../src/models/User';
import OfferRedemption from '../src/models/OfferRedemption';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const MONGODB_URI = process.env.MONGODB_URI || process.env.MONGODB_URI;
if (!MONGODB_URI) { console.error('MONGODB_URI not set'); process.exit(1); };
const DB_NAME = process.env.DB_NAME || 'test';

async function testRedemption() {
  try {
    console.log('🧪 Testing Offer Redemption System...\n');

    await mongoose.connect(MONGODB_URI, { dbName: DB_NAME });
    console.log('✅ Connected to MongoDB\n');

    // Test 1: Find an active offer
    console.log('📋 Test 1: Finding active offer...');
    const offer = await Offer.findOne({
      'validity.isActive': true,
      'validity.endDate': { $gte: new Date() }
    });

    if (!offer) {
      console.log('❌ No active offers found');
      return;
    }

    console.log(`✅ Found offer: ${offer.title}`);
    console.log(`   Cashback: ${offer.cashbackPercentage}%\n`);

    // Test 2: Find test user
    console.log('📋 Test 2: Finding test user...');
    const user = await User.findOne({ phoneNumber: '+918210224305' });
    
    if (!user) {
      console.log('❌ Test user not found');
      return;
    }

    console.log(`✅ Found user: ${user.phoneNumber}\n`);

    // Test 3: Check existing redemptions
    console.log('📋 Test 3: Checking existing redemptions...');
    const existingRedemptions = await OfferRedemption.find({
      user: user._id,
      offer: offer._id
    });

    console.log(`   Found ${existingRedemptions.length} existing redemption(s)\n`);

    // Test 4: Create new redemption
    console.log('📋 Test 4: Creating redemption...');
    
    const redemption = new OfferRedemption({
      user: user._id,
      offer: offer._id,
      redemptionType: 'online',
      redemptionDate: new Date(),
      validityDays: 30,
      status: 'active'
      // redemptionCode and expiryDate will be auto-generated by pre-save hook
    });

    await redemption.save();
    
    console.log('✅ Redemption created successfully!');
    console.log(`   Redemption Code: ${redemption.redemptionCode}`);
    console.log(`   Status: ${redemption.status}`);
    console.log(`   Expires: ${redemption.expiryDate.toLocaleDateString()}\n`);

    // Test 5: Fetch user's redemptions
    console.log('📋 Test 5: Fetching all user redemptions...');
    const allRedemptions = await OfferRedemption.find({ user: user._id })
      .populate('offer', 'title cashbackPercentage')
      .sort({ redemptionDate: -1 })
      .limit(5);

    console.log(`✅ Found ${allRedemptions.length} total redemption(s):`);
    allRedemptions.forEach((r: any, i: number) => {
      console.log(`   ${i + 1}. ${r.offer?.title || 'Unknown'}`);
      console.log(`      Code: ${r.redemptionCode}`);
      console.log(`      Status: ${r.status}`);
    });
    console.log('');

    // Test 6: Mark as used
    console.log('📋 Test 6: Testing mark as used...');
    redemption.status = 'used';
    redemption.usedDate = new Date();
    redemption.usedAmount = 50;
    await redemption.save();

    console.log('✅ Redemption marked as used\n');

    // Summary
    console.log('═'.repeat(50));
    console.log('✅ ALL TESTS PASSED!');
    console.log('═'.repeat(50));
    console.log('✅ Offer redemption system is working');
    console.log('✅ Database integration successful');
    console.log('✅ Redemption code generation working');
    console.log('✅ Status management working');
    console.log('═'.repeat(50));
    console.log('\n🎉 Offer Redemption System is Production Ready!\n');

  } catch (error) {
    console.error('❌ Test failed:', error);
  } finally {
    await mongoose.connection.close();
    console.log('🔌 Disconnected from MongoDB');
  }
}

testRedemption();

