/**
 * Bank Offer Seeds - Indian Banks & Wallets
 */

import { IBankOffer } from '../../models/BankOffer';

const futureDate = (days: number) => new Date(Date.now() + days * 24 * 60 * 60 * 1000);
const pastDate = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000);

const getPlaceholderLogo = (name: string, id: number) =>
  `https://picsum.photos/seed/bank${name}${id}/200/200`;

export const bankOfferSeeds: Partial<IBankOffer>[] = [
  // Credit Cards
  {
    bankName: 'HDFC Bank',
    bankLogo: getPlaceholderLogo('hdfc', 1),
    bankCode: 'HDFC',
    offerTitle: '15% Cashback on HDFC Credit Cards',
    offerDescription: 'Get 15% instant cashback on all purchases above Rs. 500',
    discountPercentage: 15,
    maxDiscount: 200,
    minTransactionAmount: 500,
    cardType: 'credit',
    cardNetwork: 'Visa',
    validFrom: pastDate(7),
    validUntil: futureDate(30),
    terms: 'Valid on HDFC credit cards only. Maximum cashback Rs. 200 per transaction.',
    termsDetailed: [
      'Valid on HDFC Visa and Mastercard credit cards',
      'Minimum transaction amount Rs. 500',
      'Maximum cashback Rs. 200 per transaction',
      'Offer valid once per card per day',
      'Cannot be combined with other bank offers',
    ],
    promoCode: 'HDFC15',
    usageLimitPerUser: 3,
    totalUsageLimit: 10000,
    usageCount: 4523,
    isActive: true,
    priority: 100,
  },
  {
    bankName: 'ICICI Bank',
    bankLogo: getPlaceholderLogo('icici', 2),
    bankCode: 'ICICI',
    offerTitle: '10% Instant Discount',
    offerDescription: 'Flat 10% off on all debit card transactions',
    discountPercentage: 10,
    maxDiscount: 150,
    minTransactionAmount: 400,
    cardType: 'debit',
    validFrom: pastDate(14),
    validUntil: futureDate(21),
    terms: 'Valid on all ICICI Bank debit cards',
    termsDetailed: [
      'Valid on ICICI debit cards',
      'Minimum transaction Rs. 400',
      'Maximum discount Rs. 150',
    ],
    promoCode: 'ICICI10',
    usageLimitPerUser: 2,
    usageCount: 3210,
    isActive: true,
    priority: 95,
  },
  {
    bankName: 'SBI Card',
    bankLogo: getPlaceholderLogo('sbi', 3),
    bankCode: 'SBI',
    offerTitle: '20% Cashback on SBI Credit Cards',
    offerDescription: 'Get 20% cashback on weekend transactions',
    discountPercentage: 20,
    maxDiscount: 300,
    minTransactionAmount: 750,
    cardType: 'credit',
    validFrom: pastDate(3),
    validUntil: futureDate(45),
    terms: 'Valid on weekends only (Saturday & Sunday)',
    termsDetailed: [
      'Valid only on weekends',
      'Applicable on SBI credit cards',
      'Min transaction Rs. 750',
      'Max cashback Rs. 300',
    ],
    promoCode: 'SBIWEEKEND',
    usageLimitPerUser: 2,
    usageCount: 1890,
    isActive: true,
    priority: 92,
  },
  {
    bankName: 'Axis Bank',
    bankLogo: getPlaceholderLogo('axis', 4),
    bankCode: 'AXIS',
    offerTitle: '12% Instant Discount',
    offerDescription: 'Flat 12% off on Axis Bank cards',
    discountPercentage: 12,
    maxDiscount: 250,
    minTransactionAmount: 600,
    cardType: 'all',
    validFrom: pastDate(5),
    validUntil: futureDate(25),
    terms: 'Valid on all Axis Bank credit and debit cards',
    termsDetailed: [
      'Valid on credit and debit cards',
      'Minimum purchase Rs. 600',
    ],
    promoCode: 'AXIS12',
    usageLimitPerUser: 3,
    usageCount: 2450,
    isActive: true,
    priority: 88,
  },

  // Wallets
  {
    bankName: 'Paytm',
    bankLogo: getPlaceholderLogo('paytm', 5),
    bankCode: 'PAYTM',
    offerTitle: '20% Cashback on Paytm Wallet',
    offerDescription: 'Pay via Paytm wallet and get 20% cashback',
    discountPercentage: 20,
    maxDiscount: 100,
    minTransactionAmount: 200,
    cardType: 'wallet',
    validFrom: pastDate(2),
    validUntil: futureDate(14),
    terms: 'Pay using Paytm Wallet. Cashback credited within 24 hours.',
    termsDetailed: [
      'Use Paytm Wallet for payment',
      'Minimum order Rs. 200',
      'Maximum cashback Rs. 100',
      'Cashback credited to Paytm wallet',
    ],
    usageLimitPerUser: 5,
    usageCount: 8900,
    isActive: true,
    priority: 90,
  },
  {
    bankName: 'PhonePe',
    bankLogo: getPlaceholderLogo('phonepe', 6),
    bankCode: 'PHONEPE',
    offerTitle: 'Flat Rs. 50 Cashback',
    offerDescription: 'Get Rs. 50 cashback on PhonePe payments',
    discountPercentage: 0,
    maxDiscount: 50,
    minTransactionAmount: 300,
    cardType: 'wallet',
    validFrom: pastDate(1),
    validUntil: futureDate(10),
    terms: 'First 2 transactions per user. Minimum order Rs. 300.',
    termsDetailed: [
      'Valid for first 2 transactions',
      'Pay via PhonePe UPI or wallet',
      'Minimum transaction Rs. 300',
      'Flat Rs. 50 cashback per transaction',
    ],
    usageLimitPerUser: 2,
    usageCount: 12500,
    isActive: true,
    priority: 88,
  },
  {
    bankName: 'Google Pay',
    bankLogo: getPlaceholderLogo('gpay', 7),
    bankCode: 'GPAY',
    offerTitle: 'Scratch Card up to Rs. 100',
    offerDescription: 'Pay with GPay and win scratch cards',
    discountPercentage: 0,
    maxDiscount: 100,
    minTransactionAmount: 150,
    cardType: 'upi',
    validFrom: pastDate(3),
    validUntil: futureDate(30),
    terms: 'Scratch card rewards vary. Minimum transaction Rs. 150.',
    termsDetailed: [
      'Pay using Google Pay UPI',
      'Receive scratch card after payment',
      'Win rewards up to Rs. 100',
    ],
    usageCount: 25000,
    isActive: true,
    priority: 85,
  },
  {
    bankName: 'Amazon Pay',
    bankLogo: getPlaceholderLogo('amazonpay', 8),
    bankCode: 'AMAZONPAY',
    offerTitle: '10% Amazon Pay Balance Cashback',
    offerDescription: 'Get 10% cashback when paying with Amazon Pay balance',
    discountPercentage: 10,
    maxDiscount: 75,
    minTransactionAmount: 250,
    cardType: 'wallet',
    validFrom: pastDate(7),
    validUntil: futureDate(21),
    terms: 'Load Amazon Pay balance and get additional cashback',
    termsDetailed: [
      'Use Amazon Pay balance for payment',
      'Cashback credited to Amazon Pay',
      'Maximum cashback Rs. 75',
    ],
    usageLimitPerUser: 3,
    usageCount: 6700,
    isActive: true,
    priority: 82,
  },
];

export default bankOfferSeeds;
