/**
 * Exclusive Zone Seeds
 * User segment categories like Corporate, Women, Birthday, Student
 */

import { IExclusiveZone } from '../../models/ExclusiveZone';

export const exclusiveZoneSeeds: Partial<IExclusiveZone>[] = [
  {
    name: 'Student',
    slug: 'student',
    icon: 'school',
    iconColor: '#6366F1',
    backgroundColor: '#EEF2FF',
    description: 'Exclusive offers for students with valid ID',
    shortDescription: 'Student discounts up to 30%',
    eligibilityType: 'student',
    eligibilityDetails: 'Valid student ID or .edu email required',
    verificationRequired: true,
    offersCount: 34,
    isActive: true,
    priority: 100,
  },
  {
    name: 'Corporate',
    slug: 'corporate',
    icon: 'briefcase',
    iconColor: '#0EA5E9',
    backgroundColor: '#E0F2FE',
    description: 'Special deals for corporate employees',
    shortDescription: 'Corporate perks & discounts',
    eligibilityType: 'corporate_email',
    eligibilityDetails: 'Valid corporate email required',
    verificationRequired: true,
    offersCount: 28,
    isActive: true,
    priority: 95,
  },
  {
    name: 'Women',
    slug: 'women',
    icon: 'woman',
    iconColor: '#EC4899',
    backgroundColor: '#FCE7F3',
    description: 'Exclusive offers curated for women',
    shortDescription: 'Women-only deals',
    eligibilityType: 'gender',
    eligibilityDetails: 'Self-declaration in profile',
    verificationRequired: false,
    offersCount: 45,
    isActive: true,
    priority: 90,
  },
  {
    name: 'Birthday',
    slug: 'birthday',
    icon: 'gift',
    iconColor: '#F59E0B',
    backgroundColor: '#FEF3C7',
    description: 'Special treats during your birthday month',
    shortDescription: 'Birthday month specials',
    eligibilityType: 'birthday_month',
    eligibilityDetails: 'Valid during your birthday month',
    verificationRequired: false,
    offersCount: 12,
    isActive: true,
    priority: 88,
  },
  {
    name: 'Senior Citizen',
    slug: 'senior',
    icon: 'heart',
    iconColor: '#10B981',
    backgroundColor: '#D1FAE5',
    description: 'Exclusive discounts for senior citizens (60+)',
    shortDescription: 'Senior citizen benefits',
    eligibilityType: 'age',
    eligibilityDetails: 'Age 60+ verification required',
    verificationRequired: true,
    offersCount: 18,
    isActive: true,
    priority: 85,
  },
  {
    name: 'First Time User',
    slug: 'first-time',
    icon: 'star',
    iconColor: '#8B5CF6',
    backgroundColor: '#EDE9FE',
    description: 'Welcome offers for new users',
    shortDescription: 'New user welcome deals',
    eligibilityType: 'verification',
    eligibilityDetails: 'First order only',
    verificationRequired: false,
    offersCount: 25,
    isActive: true,
    priority: 92,
  },
  {
    name: 'Defence',
    slug: 'defence',
    icon: 'shield-checkmark',
    iconColor: '#15803D',
    backgroundColor: '#DCFCE7',
    description: 'Exclusive offers for defence personnel and veterans',
    shortDescription: 'Defence & veteran benefits',
    eligibilityType: 'profession',
    eligibilityDetails: 'Valid defence/military ID required',
    verificationRequired: true,
    offersCount: 0,
    isActive: true,
    priority: 82,
    cashbackBonusPercent: 10,
  },
  {
    name: 'Healthcare',
    slug: 'healthcare',
    icon: 'medkit',
    iconColor: '#DC2626',
    backgroundColor: '#FEE2E2',
    description: 'Special discounts for healthcare professionals',
    shortDescription: 'Healthcare worker perks',
    eligibilityType: 'profession',
    eligibilityDetails: 'Valid medical/healthcare ID required',
    verificationRequired: true,
    offersCount: 0,
    isActive: true,
    priority: 80,
    cashbackBonusPercent: 8,
  },
  {
    name: 'Educator',
    slug: 'teacher',
    icon: 'library',
    iconColor: '#7C3AED',
    backgroundColor: '#EDE9FE',
    description: 'Exclusive benefits for teachers and educators',
    shortDescription: 'Educator discounts',
    eligibilityType: 'profession',
    eligibilityDetails: 'Valid teacher/educator ID required',
    verificationRequired: true,
    offersCount: 0,
    isActive: true,
    priority: 78,
    cashbackBonusPercent: 8,
  },
  {
    name: 'Government',
    slug: 'government',
    icon: 'business',
    iconColor: '#B45309',
    backgroundColor: '#FEF3C7',
    description: 'Special offers for government employees',
    shortDescription: 'Government employee perks',
    eligibilityType: 'profession',
    eligibilityDetails: 'Valid government employee ID required',
    verificationRequired: true,
    offersCount: 0,
    isActive: true,
    priority: 75,
    cashbackBonusPercent: 5,
  },
  {
    name: 'Differently Abled',
    slug: 'differently-abled',
    icon: 'accessibility',
    iconColor: '#0891B2',
    backgroundColor: '#CFFAFE',
    description: 'Inclusive offers for differently abled individuals',
    shortDescription: 'Accessibility benefits',
    eligibilityType: 'disability',
    eligibilityDetails: 'Valid disability certificate required',
    verificationRequired: true,
    offersCount: 0,
    isActive: true,
    priority: 83,
    cashbackBonusPercent: 10,
  },
];

export default exclusiveZoneSeeds;
