/**
 * Hotspot Area Seeds - Indian Cities/Areas
 */

import mongoose from 'mongoose';
import { IHotspotArea } from '../../models/HotspotArea';

const getPlaceholderImage = (name: string, id: number) =>
  `https://picsum.photos/seed/hotspot${name}${id}/400/200`;

export const hotspotSeeds: Partial<IHotspotArea>[] = [
  // Bangalore Areas
  {
    name: 'Koramangala',
    slug: 'koramangala',
    coordinates: { lat: 12.9352, lng: 77.6245 },
    radius: 3,
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    image: getPlaceholderImage('koramangala', 1),
    isActive: true,
    priority: 100,
    totalDeals: 45,
  },
  {
    name: 'Indiranagar',
    slug: 'indiranagar',
    coordinates: { lat: 12.9719, lng: 77.6411 },
    radius: 3,
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    image: getPlaceholderImage('indiranagar', 2),
    isActive: true,
    priority: 95,
    totalDeals: 38,
  },
  {
    name: 'HSR Layout',
    slug: 'hsr-layout',
    coordinates: { lat: 12.9116, lng: 77.6389 },
    radius: 3,
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    image: getPlaceholderImage('hsr', 3),
    isActive: true,
    priority: 90,
    totalDeals: 32,
  },
  {
    name: 'Whitefield',
    slug: 'whitefield',
    coordinates: { lat: 12.9698, lng: 77.7500 },
    radius: 5,
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    image: getPlaceholderImage('whitefield', 4),
    isActive: true,
    priority: 85,
    totalDeals: 28,
  },
  {
    name: 'Electronic City',
    slug: 'electronic-city',
    coordinates: { lat: 12.8399, lng: 77.6770 },
    radius: 5,
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    image: getPlaceholderImage('ecity', 5),
    isActive: true,
    priority: 80,
    totalDeals: 25,
  },
  {
    name: 'MG Road',
    slug: 'mg-road',
    coordinates: { lat: 12.9757, lng: 77.6064 },
    radius: 2,
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    image: getPlaceholderImage('mgroad', 6),
    isActive: true,
    priority: 88,
    totalDeals: 35,
  },
  {
    name: 'Jayanagar',
    slug: 'jayanagar',
    coordinates: { lat: 12.9300, lng: 77.5800 },
    radius: 3,
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    image: getPlaceholderImage('jayanagar', 7),
    isActive: true,
    priority: 75,
    totalDeals: 22,
  },
  {
    name: 'BTM Layout',
    slug: 'btm-layout',
    coordinates: { lat: 12.9166, lng: 77.6101 },
    radius: 3,
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    image: getPlaceholderImage('btm', 8),
    isActive: true,
    priority: 78,
    totalDeals: 30,
  },

  // Mumbai Areas
  {
    name: 'Bandra',
    slug: 'bandra',
    coordinates: { lat: 19.0596, lng: 72.8295 },
    radius: 3,
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    image: getPlaceholderImage('bandra', 9),
    isActive: true,
    priority: 92,
    totalDeals: 40,
  },
  {
    name: 'Andheri',
    slug: 'andheri',
    coordinates: { lat: 19.1136, lng: 72.8697 },
    radius: 4,
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    image: getPlaceholderImage('andheri', 10),
    isActive: true,
    priority: 88,
    totalDeals: 35,
  },

  // Delhi Areas
  {
    name: 'Connaught Place',
    slug: 'connaught-place',
    coordinates: { lat: 28.6315, lng: 77.2167 },
    radius: 2,
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    image: getPlaceholderImage('cp', 11),
    isActive: true,
    priority: 95,
    totalDeals: 50,
  },
  {
    name: 'Hauz Khas',
    slug: 'hauz-khas',
    coordinates: { lat: 28.5494, lng: 77.2001 },
    radius: 2,
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    image: getPlaceholderImage('hauzkhas', 12),
    isActive: true,
    priority: 85,
    totalDeals: 28,
  },

  // Dubai Areas
  {
    name: 'Dubai Mall',
    slug: 'dubai-mall',
    coordinates: { lat: 25.1972, lng: 55.2796 },
    radius: 2,
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    image: getPlaceholderImage('dubaimall', 13),
    isActive: true,
    priority: 100,
    totalDeals: 60,
  },
  {
    name: 'Mall of the Emirates',
    slug: 'mall-of-the-emirates',
    coordinates: { lat: 25.1181, lng: 55.2008 },
    radius: 2,
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    image: getPlaceholderImage('moe', 14),
    isActive: true,
    priority: 95,
    totalDeals: 52,
  },
  {
    name: 'JBR Walk',
    slug: 'jbr-walk',
    coordinates: { lat: 25.0783, lng: 55.1340 },
    radius: 3,
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    image: getPlaceholderImage('jbr', 15),
    isActive: true,
    priority: 90,
    totalDeals: 38,
  },
  {
    name: 'DIFC',
    slug: 'difc',
    coordinates: { lat: 25.2100, lng: 55.2780 },
    radius: 2,
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    image: getPlaceholderImage('difc', 16),
    isActive: true,
    priority: 88,
    totalDeals: 30,
  },
  {
    name: 'Deira City Centre',
    slug: 'deira-city-centre',
    coordinates: { lat: 25.2520, lng: 55.3305 },
    radius: 3,
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    image: getPlaceholderImage('deira', 17),
    isActive: true,
    priority: 82,
    totalDeals: 35,
  },
  {
    name: 'Ibn Battuta Mall',
    slug: 'ibn-battuta-mall',
    coordinates: { lat: 25.0441, lng: 55.1182 },
    radius: 2,
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    image: getPlaceholderImage('ibnbattuta', 18),
    isActive: true,
    priority: 78,
    totalDeals: 28,
  },
  {
    name: 'Dubai Marina Mall',
    slug: 'dubai-marina-mall',
    coordinates: { lat: 25.0770, lng: 55.1398 },
    radius: 2,
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    image: getPlaceholderImage('marinamall', 19),
    isActive: true,
    priority: 85,
    totalDeals: 32,
  },
  {
    name: 'City Walk',
    slug: 'city-walk',
    coordinates: { lat: 25.2082, lng: 55.2638 },
    radius: 2,
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    image: getPlaceholderImage('citywalk', 20),
    isActive: true,
    priority: 87,
    totalDeals: 25,
  },
];

export default hotspotSeeds;
