/**
 * Loyalty Milestone Seeds
 * User loyalty progress milestones
 */

import { ILoyaltyMilestone } from '../../models/LoyaltyMilestone';

export const loyaltyMilestoneSeeds: Partial<ILoyaltyMilestone>[] = [
  // Order-based milestones
  {
    title: 'Order 3 more times',
    description: 'Complete to unlock Gold status',
    targetType: 'orders',
    targetValue: 10,
    reward: 'Gold Member',
    rewardType: 'tier_upgrade',
    rewardCoins: 500,
    icon: 'trophy',
    color: '#F59E0B',
    tier: 'gold',
    order: 1,
    isActive: true,
  },
  {
    title: 'First 5 Orders',
    description: 'Complete 5 orders to earn bonus coins',
    targetType: 'orders',
    targetValue: 5,
    reward: '200 Bonus Coins',
    rewardType: 'coins',
    rewardCoins: 200,
    icon: 'cart',
    color: '#10B981',
    order: 2,
    isActive: true,
  },
  {
    title: 'Super Shopper',
    description: 'Complete 25 orders this month',
    targetType: 'orders',
    targetValue: 25,
    reward: 'Super Shopper Badge',
    rewardType: 'badge',
    rewardCoins: 1000,
    icon: 'star',
    color: '#8B5CF6',
    order: 3,
    isActive: true,
  },

  // Spend-based milestones
  {
    title: 'Spend Rs. 5,000',
    description: 'Unlock exclusive member benefits',
    targetType: 'spend',
    targetValue: 5000,
    reward: 'Silver Member',
    rewardType: 'tier_upgrade',
    rewardCoins: 250,
    icon: 'wallet',
    color: '#6B7280',
    tier: 'silver',
    order: 4,
    isActive: true,
  },
  {
    title: 'Big Spender',
    description: 'Spend Rs. 20,000 to unlock Platinum',
    targetType: 'spend',
    targetValue: 20000,
    reward: 'Platinum Member',
    rewardType: 'tier_upgrade',
    rewardCoins: 2000,
    icon: 'diamond',
    color: '#A78BFA',
    tier: 'platinum',
    order: 5,
    isActive: true,
  },

  // Referral-based milestones
  {
    title: 'Refer 3 Friends',
    description: 'Get bonus coins for each referral',
    targetType: 'referrals',
    targetValue: 3,
    reward: '300 Bonus Coins',
    rewardType: 'coins',
    rewardCoins: 300,
    icon: 'people',
    color: '#3B82F6',
    order: 6,
    isActive: true,
  },
  {
    title: 'Referral Champion',
    description: 'Refer 10 friends to unlock special rewards',
    targetType: 'referrals',
    targetValue: 10,
    reward: 'Referral Champion Badge + 1000 Coins',
    rewardType: 'badge',
    rewardCoins: 1000,
    icon: 'medal',
    color: '#F97316',
    order: 7,
    isActive: true,
  },

  // Review-based milestones
  {
    title: 'First Review',
    description: 'Write your first product review',
    targetType: 'reviews',
    targetValue: 1,
    reward: '50 Bonus Coins',
    rewardType: 'coins',
    rewardCoins: 50,
    icon: 'chatbubble',
    color: '#06B6D4',
    order: 8,
    isActive: true,
  },
  {
    title: 'Review Expert',
    description: 'Write 10 reviews to earn expert badge',
    targetType: 'reviews',
    targetValue: 10,
    reward: 'Review Expert Badge',
    rewardType: 'badge',
    rewardCoins: 500,
    icon: 'create',
    color: '#EC4899',
    order: 9,
    isActive: true,
  },

  // Check-in based milestones
  {
    title: '7-Day Streak',
    description: 'Check in for 7 consecutive days',
    targetType: 'checkins',
    targetValue: 7,
    reward: '100 Bonus Coins',
    rewardType: 'coins',
    rewardCoins: 100,
    icon: 'flame',
    color: '#EF4444',
    order: 10,
    isActive: true,
  },
  {
    title: '30-Day Warrior',
    description: 'Maintain a 30-day check-in streak',
    targetType: 'checkins',
    targetValue: 30,
    reward: 'Warrior Badge + 500 Coins',
    rewardType: 'badge',
    rewardCoins: 500,
    icon: 'ribbon',
    color: '#DC2626',
    order: 11,
    isActive: true,
  },
];

export default loyaltyMilestoneSeeds;
