/**
 * Special Profile Seeds
 * Verified profile categories like Defence, Healthcare, Senior Citizens
 */

import { ISpecialProfile } from '../../models/SpecialProfile';

export const specialProfileSeeds: Partial<ISpecialProfile>[] = [
  {
    name: 'Defence',
    slug: 'defence',
    icon: 'shield',
    iconColor: '#059669',
    backgroundColor: '#D1FAE5',
    description: 'Exclusive offers for Indian Armed Forces personnel',
    verificationRequired: 'Military ID / Service Card',
    verificationDocuments: ['Military ID', 'Service Card', 'Canteen Card', 'Ex-Servicemen Card'],
    verificationTime: '24-48 hours',
    offersCount: 25,
    discountRange: '15-40%',
    benefits: [
      'Up to 40% discount on select brands',
      'Priority customer support',
      'Free delivery on all orders',
      'Exclusive defence day sales',
    ],
    isActive: true,
    priority: 100,
  },
  {
    name: 'Healthcare Workers',
    slug: 'healthcare',
    icon: 'medkit',
    iconColor: '#DC2626',
    backgroundColor: '#FEE2E2',
    description: 'Special deals for doctors, nurses, and healthcare professionals',
    verificationRequired: 'Hospital ID / Medical Council Registration',
    verificationDocuments: ['Hospital ID', 'Medical Council Certificate', 'Nursing License'],
    verificationTime: '24-48 hours',
    offersCount: 22,
    discountRange: '10-30%',
    benefits: [
      'Healthcare worker discounts',
      'Free health check-up vouchers',
      'Wellness product offers',
      'Flexible delivery slots',
    ],
    isActive: true,
    priority: 95,
  },
  {
    name: 'Senior Citizens',
    slug: 'senior',
    icon: 'heart',
    iconColor: '#7C3AED',
    backgroundColor: '#EDE9FE',
    description: 'Benefits for citizens aged 60 and above',
    verificationRequired: 'Aadhar Card / Age Proof',
    verificationDocuments: ['Aadhar Card', 'Passport', 'Voter ID'],
    verificationTime: '24 hours',
    offersCount: 20,
    discountRange: '10-25%',
    benefits: [
      'Senior citizen discounts',
      'Free home delivery',
      'Easy return policy',
      'Dedicated helpline',
    ],
    isActive: true,
    priority: 90,
  },
  {
    name: 'Teachers',
    slug: 'teachers',
    icon: 'book',
    iconColor: '#2563EB',
    backgroundColor: '#DBEAFE',
    description: 'Appreciation offers for educators',
    verificationRequired: 'School/College ID',
    verificationDocuments: ['School ID', 'College ID', 'UGC ID', 'Teacher Registration Certificate'],
    verificationTime: '24-48 hours',
    offersCount: 18,
    discountRange: '10-25%',
    benefits: [
      'Special discounts on books and stationery',
      'Educational subscriptions at reduced prices',
      'Free access to premium content',
    ],
    isActive: true,
    priority: 85,
  },
  {
    name: 'Government Employees',
    slug: 'government',
    icon: 'business',
    iconColor: '#0891B2',
    backgroundColor: '#CFFAFE',
    description: 'Exclusive offers for government sector employees',
    verificationRequired: 'Government ID Card',
    verificationDocuments: ['Government ID', 'Pay Slip', 'Office Order'],
    verificationTime: '48 hours',
    offersCount: 15,
    discountRange: '10-20%',
    benefits: [
      'Government employee discounts',
      'EMI options available',
      'Special festive offers',
    ],
    isActive: true,
    priority: 80,
  },
  {
    name: 'Differently Abled',
    slug: 'differently-abled',
    icon: 'accessibility',
    iconColor: '#EA580C',
    backgroundColor: '#FFEDD5',
    description: 'Special benefits for differently abled individuals',
    verificationRequired: 'Disability Certificate',
    verificationDocuments: ['Disability Certificate', 'UDID Card'],
    verificationTime: '24 hours',
    offersCount: 12,
    discountRange: '15-30%',
    benefits: [
      'Priority assistance',
      'Accessible delivery options',
      'Special discounts',
      'Free doorstep delivery',
    ],
    isActive: true,
    priority: 88,
  },
];

export default specialProfileSeeds;
