/**
 * Upload Bill Store Seeds
 * Stores that accept bill uploads for cashback
 */

import { IUploadBillStore } from '../../models/UploadBillStore';

const getPlaceholderLogo = (name: string, id: number) =>
  `https://picsum.photos/seed/bill${name}${id}/200/200`;

export const uploadBillStoreSeeds: Partial<IUploadBillStore>[] = [
  {
    name: 'Big Bazaar',
    logo: getPlaceholderLogo('bigbazaar', 1),
    category: 'Grocery',
    coinsPerRupee: 2,
    maxCoinsPerBill: 500,
    minBillAmount: 200,
    verificationRequired: true,
    verificationTime: '24-48 hours',
    instructions: [
      'Take a clear photo of the complete bill',
      'Ensure the store name and total amount are visible',
      'Bill must be dated within last 7 days',
    ],
    acceptedBillTypes: ['receipt', 'invoice'],
    isActive: true,
    priority: 100,
    totalUploads: 15000,
  },
  {
    name: 'DMart',
    logo: getPlaceholderLogo('dmart', 2),
    category: 'Grocery',
    coinsPerRupee: 3,
    maxCoinsPerBill: 750,
    minBillAmount: 300,
    verificationRequired: true,
    verificationTime: '24 hours',
    instructions: [
      'Upload the printed receipt',
      'Make sure bill number is clearly visible',
      'Maximum 2 bills per day',
    ],
    acceptedBillTypes: ['receipt'],
    isActive: true,
    priority: 95,
    totalUploads: 12500,
  },
  {
    name: 'Reliance Fresh',
    logo: getPlaceholderLogo('reliance', 3),
    category: 'Grocery',
    coinsPerRupee: 2,
    maxCoinsPerBill: 400,
    minBillAmount: 150,
    verificationRequired: true,
    verificationTime: '24-48 hours',
    instructions: [
      'Clear photo of complete bill required',
      'Bill must include store address',
    ],
    acceptedBillTypes: ['receipt', 'invoice'],
    isActive: true,
    priority: 90,
    totalUploads: 8900,
  },
  {
    name: 'Spencer\'s',
    logo: getPlaceholderLogo('spencers', 4),
    category: 'Grocery',
    coinsPerRupee: 2,
    maxCoinsPerBill: 350,
    minBillAmount: 200,
    verificationRequired: true,
    verificationTime: '48 hours',
    instructions: [
      'Upload original receipt only',
      'No photocopies accepted',
    ],
    acceptedBillTypes: ['receipt'],
    isActive: true,
    priority: 85,
    totalUploads: 5600,
  },
  {
    name: 'Croma',
    logo: getPlaceholderLogo('croma', 5),
    category: 'Electronics',
    coinsPerRupee: 5,
    maxCoinsPerBill: 2000,
    minBillAmount: 2000,
    verificationRequired: true,
    verificationTime: '48-72 hours',
    instructions: [
      'Upload GST invoice',
      'Product serial number must be visible',
      'Valid for electronics purchases only',
    ],
    acceptedBillTypes: ['gst_invoice', 'invoice'],
    isActive: true,
    priority: 92,
    totalUploads: 3200,
  },
  {
    name: 'Vijay Sales',
    logo: getPlaceholderLogo('vijaysales', 6),
    category: 'Electronics',
    coinsPerRupee: 4,
    maxCoinsPerBill: 1500,
    minBillAmount: 1500,
    verificationRequired: true,
    verificationTime: '48-72 hours',
    instructions: [
      'GST invoice required',
      'Valid for all electronics',
    ],
    acceptedBillTypes: ['gst_invoice'],
    isActive: true,
    priority: 88,
    totalUploads: 2100,
  },
  {
    name: 'Decathlon',
    logo: getPlaceholderLogo('decathlon', 7),
    category: 'Sports',
    coinsPerRupee: 3,
    maxCoinsPerBill: 600,
    minBillAmount: 500,
    verificationRequired: true,
    verificationTime: '24-48 hours',
    instructions: [
      'Upload store receipt',
      'Online order confirmations also accepted',
    ],
    acceptedBillTypes: ['receipt', 'online_order'],
    isActive: true,
    priority: 80,
    totalUploads: 4500,
  },
  {
    name: 'Apollo Pharmacy',
    logo: getPlaceholderLogo('apollo', 8),
    category: 'Pharmacy',
    coinsPerRupee: 2,
    maxCoinsPerBill: 200,
    minBillAmount: 100,
    verificationRequired: true,
    verificationTime: '24 hours',
    instructions: [
      'Upload pharmacy bill',
      'Prescription medicines eligible',
    ],
    acceptedBillTypes: ['receipt', 'invoice'],
    isActive: true,
    priority: 75,
    totalUploads: 7800,
  },
];

export default uploadBillStoreSeeds;
