/**
 * PriveInviteCode Model
 *
 * Tracks invite codes generated by Privé members for inviting new users.
 * Each code has a configurable usage limit and expiry.
 */

import mongoose, { Schema, Document, Types, Model } from 'mongoose';
import crypto from 'crypto';

export interface IPriveInviteCodeUsage {
  userId: Types.ObjectId;
  usedAt: Date;
  rewardDistributed: boolean;
}

export interface IPriveInviteCode extends Document {
  _id: Types.ObjectId;
  code: string;
  creatorId: Types.ObjectId;
  creatorTier: 'entry' | 'signature' | 'elite';

  // Usage tracking
  usageCount: number;
  maxUses: number;
  usedBy: IPriveInviteCodeUsage[];

  // Validity
  isActive: boolean;
  expiresAt: Date;
  deactivatedAt?: Date;
  deactivationReason?: string;

  // Metadata for fraud detection
  metadata: {
    createdFromIP?: string;
    createdFromDevice?: string;
  };

  createdAt: Date;
  updatedAt: Date;
}

export interface IPriveInviteCodeModel extends Model<IPriveInviteCode> {
  generateUniqueCode(): Promise<string>;
  getActiveCodesByCreator(creatorId: string | Types.ObjectId): Promise<IPriveInviteCode[]>;
  findByCode(code: string): Promise<IPriveInviteCode | null>;
}

const PriveInviteCodeUsageSchema = new Schema<IPriveInviteCodeUsage>(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    usedAt: {
      type: Date,
      default: Date.now,
    },
    rewardDistributed: {
      type: Boolean,
      default: false,
    },
  },
  { _id: false }
);

const PriveInviteCodeSchema = new Schema<IPriveInviteCode>(
  {
    code: {
      type: String,
      required: [true, 'Invite code is required'],
      unique: true,
      uppercase: true,
      trim: true,
    },
    creatorId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Creator ID is required'],
      index: true,
    },
    creatorTier: {
      type: String,
      enum: ['entry', 'signature', 'elite'],
      required: [true, 'Creator tier is required'],
    },

    // Usage
    usageCount: {
      type: Number,
      default: 0,
      min: 0,
    },
    maxUses: {
      type: Number,
      default: 5,
      min: 1,
    },
    usedBy: {
      type: [PriveInviteCodeUsageSchema],
      default: [],
    },

    // Validity
    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },
    expiresAt: {
      type: Date,
      required: [true, 'Expiry date is required'],
      index: true,
    },
    deactivatedAt: {
      type: Date,
    },
    deactivationReason: {
      type: String,
    },

    // Metadata
    metadata: {
      type: Schema.Types.Mixed,
      default: {},
    },
  },
  {
    timestamps: true,
  }
);

// Compound indexes
PriveInviteCodeSchema.index({ creatorId: 1, isActive: 1 });
PriveInviteCodeSchema.index({ creatorId: 1, createdAt: -1 });
PriveInviteCodeSchema.index({ code: 1 }, { unique: true });

// Generate unique invite code: PRIVE-XXXXXXXX
PriveInviteCodeSchema.statics.generateUniqueCode = async function (): Promise<string> {
  const characters = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // No 0/O/1/I
  let code: string;
  let exists = true;

  while (exists) {
    let random = '';
    for (let i = 0; i < 8; i++) {
      random += characters.charAt(crypto.randomInt(characters.length));
    }
    code = `PRIVE-${random}`;
    exists = !!(await this.findOne({ code }));
  }

  return code!;
};

// Get active codes by creator
PriveInviteCodeSchema.statics.getActiveCodesByCreator = async function (
  creatorId: string | Types.ObjectId
): Promise<IPriveInviteCode[]> {
  const now = new Date();
  return this.find({
    creatorId,
    isActive: true,
    expiresAt: { $gt: now },
  }).sort({ createdAt: -1 });
};

// Find by code string
PriveInviteCodeSchema.statics.findByCode = async function (
  code: string
): Promise<IPriveInviteCode | null> {
  return this.findOne({ code: code.toUpperCase().trim() });
};

// Virtual: is code still valid
PriveInviteCodeSchema.virtual('isValid').get(function () {
  return this.isActive && new Date() < this.expiresAt && this.usageCount < this.maxUses;
});

// Pre-save: auto-deactivate if expired
PriveInviteCodeSchema.pre('save', function (next) {
  if (this.expiresAt && new Date() > this.expiresAt && this.isActive) {
    this.isActive = false;
    this.deactivatedAt = new Date();
    this.deactivationReason = 'expired';
  }
  next();
});

const PriveInviteCode = mongoose.model<IPriveInviteCode, IPriveInviteCodeModel>(
  'PriveInviteCode',
  PriveInviteCodeSchema
);

export default PriveInviteCode;
