/**
 * QrShortLink — compact tokens behind `rez.money/q/<token>` short URLs.
 *
 * A single store's printed placard might encode a URL (easier to
 * update — flip the DB row, the pre-printed QR keeps working) rather
 * than the raw JSON payload. This model stores the token → payload
 * map. A TTL index deletes expired links automatically.
 *
 * Tokens are generated by `crypto.randomBytes(8).toString('base64url')`
 * — 11 chars, collision-resistant at ≥10^19 scale.
 */

import mongoose, { Schema, Document, Types } from 'mongoose';

export interface IQrShortLink extends Document {
  token: string;
  /** The canonical QrPayload stored verbatim. Validated on creation. */
  payload: Record<string, unknown>;
  /** Optional owning merchant — for analytics + revocation. */
  merchantId?: Types.ObjectId;
  /** Optional store scoping. */
  storeId?: Types.ObjectId;
  /** Hit counter — incremented on every resolve. Approximate analytics. */
  hits: number;
  /** When the link should self-destruct. Null = never. */
  expiresAt?: Date;
  /** Hard kill-switch independent of TTL. */
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const QrShortLinkSchema = new Schema<IQrShortLink>(
  {
    token: { type: String, required: true, unique: true, index: true, trim: true },
    payload: { type: Schema.Types.Mixed, required: true },
    merchantId: { type: Schema.Types.ObjectId, ref: 'Merchant' },
    storeId: { type: Schema.Types.ObjectId, ref: 'Store' },
    hits: { type: Number, default: 0, min: 0 },
    expiresAt: { type: Date },
    isActive: { type: Boolean, default: true, index: true },
  },
  { timestamps: true },
);

// TTL — Mongo deletes docs whose expiresAt is in the past.
QrShortLinkSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });
// Analytics query: links owned by a merchant, sorted by recency.
QrShortLinkSchema.index({ merchantId: 1, createdAt: -1 });

export const QrShortLink =
  (mongoose.models.QrShortLink as mongoose.Model<IQrShortLink>) ||
  mongoose.model<IQrShortLink>('QrShortLink', QrShortLinkSchema);

export default QrShortLink;
