apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: merchant-backend-pdb
  labels:
    app: merchant-backend
    tier: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: merchant-backend
